### ISSUE TITLE
Multiple destination

### ISSUE THREAD

**Issue by fquffio** [chialab/streamlined-backup#6]
The configuration and internal structure should be refactored to allow each Task to have multiple Destinations.

Each Destination may specify a custom schedule at which it should be executed. A Task should be run if at least one of its Destinations are due, and its output should be delivered to all destinations in parallel.

This would make it easier to organize daily and weekly backups, for example, or to upload the same backup to two distinct buckets in two separate AWS Regions and/or Accounts.

### Example configuration

TOML:

```toml
[my-backup-task]
command = ["tar", "-cvjf-", "uploaded-files/"]

    [[my-backup-task.destination]]
    type = "s3"
    schedule = "30 4 * * *"
        [my-backup-task.destination.s3]
        bucket = "example-bucket"
        prefix = "daily/"

    [[my-backup-task.destination]]
    type = "s3"
    schedule = "30 4 * * 0"
        [my-backup-task.destination.s3]
        bucket = "example-bucket"
        prefix = "weekly/"
```

JSON:

```json
{
  "my-backup-task": {
    "command": ["tar", "-cvjf-", "uploaded-files/"],
    "destination": [
      {
        "type": "s3",
        "schedule": "30 4 * * *",
        "s3": {
          "bucket": "example-bucket",
          "prefix": "daily/"
        }
      },
      {
        "type": "s3",
        "schedule": "30 4 * * 0",
        "s3": {
          "bucket": "example-bucket",
          "prefix": "weekly/"
        }
      }
    ]
  }
}
```
